version: '3.8'
 
services:
  # Book Catalog Service
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://part_3_3v4a_user:Z5yvHsrGujWMLxOWOXkrSzyUvciOdIGo@dpg-cs2cmkrqf0us73a5a2ig-a.oregon-postgres.render.com/part_3_3v4a
  # Inventory Management Service
  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://part_3_3v4a_user:Z5yvHsrGujWMLxOWOXkrSzyUvciOdIGo@dpg-cs2cmkrqf0us73a5a2ig-a.oregon-postgres.render.com/part_3_3v4a